### ISSUE TITLE
Support removing dormant accounts when notifications are disabled.

### ISSUE THREAD

**Issue by garnertb** [garnertb/dormant-accounts#26]
Currently, when running the copilot-dormancy action with the following settings, the action will not remove dormant accounts, since that functionality is implemented in the notification workflow. 

```yml
with:
    duration: 25 days
    dry-run: true
    notifications-enabled: false
    remove-dormant-accounts: true
```
